# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-09 05:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopCate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='cover_image',
            field=models.FileField(blank=True, upload_to='cover_image'),
        ),
        migrations.AddField(
            model_name='category',
            name='topcate',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='blog.TopCate'),
            preserve_default=False,
        ),
    ]
