# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-09 05:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180209_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='topcate',
            field=models.ForeignKey(default='study', on_delete=django.db.models.deletion.CASCADE, to='blog.TopCate'),
        ),
    ]
