# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-09 05:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180209_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='topcate',
            name='name',
            field=models.CharField(default='学无止境', max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='topcate',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='blog.TopCate'),
        ),
    ]
