# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-10 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180209_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cover_image',
            field=models.FileField(blank=True, upload_to='cover_image/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='cover_image',
            field=models.FileField(blank=True, upload_to='cover_image_son/%Y/%m/%d/'),
        ),
    ]
